substitutions:
  node_name: esp_bathroom_led_lights
  node_friendly_name: "Bathroom Vanity"

packages:
  esp_common: !include shared/esp__common_core.yaml

esphome:
  platform: ESP32
  board: featheresp32

script:
  # motion actiavte light
  - id: motion_activate
    mode: restart
    then:
      if:
        condition:
          - binary_sensor.is_on: bathroom_vanity_api_status
        then:
          - light.turn_on:
              id: bathroom_vanity_uplight
              transition_length: 1s
          - light.turn_on:
              id: bathroom_vanity_downlight
              transition_length: 1s
        else:
          - light.turn_on:
              id: bathroom_vanity_uplight
              transition_length: 1s
              brightness: 1.0
              red: 1.0
              green: 0.675
              blue: 0.06
              white: 1.0
          - light.turn_on:
              id: bathroom_vanity_downlight
              transition_length: 1s
              brightness: 1.0
              red: 1.0
              green: 0.675
              blue: 0.06
              white: 1.0
  # motion deactiavte light
  - id: motion_deactivate
    mode: restart
    then:
      - delay: 180s
      - light.turn_off:
          id: bathroom_vanity_uplight
          transition_length: 1s
      - light.turn_off:
          id: bathroom_vanity_downlight
          transition_length: 1s

status_led:
  pin:
    number: GPIO5
    inverted: true

binary_sensor:
  - platform: status
    id: bathroom_vanity_api_status
    name: ${node_friendly_name} API Status
    internal: true
  - platform: gpio
    id: bathroom_vanity_motion_detection
    name: ${node_friendly_name} Motion Detection
    pin:
      number: GPIO2
    on_press:
      then:
        if:
          condition:
            lambda: 'return id(bathroom_vanity_motion_activation).state || !id(bathroom_vanity_api_status).state;'
          then:
            - script.stop: motion_deactivate
            - script.execute: motion_activate
    on_release:
      then:
        if:
          condition:
            lambda: 'return id(bathroom_vanity_motion_activation).state || !id(bathroom_vanity_api_status).state;'
          then:
            - script.execute: motion_deactivate
  - platform: gpio
    id: bathroom_lights_off_button
    pin:
      number: GPIO0
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - light.turn_off:
            id: bathroom_vanity_uplight
        - light.turn_off:
            id: bathroom_vanity_downlight
  - platform: gpio
    id: bathroom_vanity_uplight_on_button
    pin:
      number: GPIO36
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - light.turn_on:
            id: bathroom_vanity_uplight
            brightness: 1.0
            red: 1.0
            green: 0.933
            blue: 0.753
            white: 1.0
  - platform: gpio
    id: bathroom_vanity_downlight_on_button
    pin:
      number: GPIO39
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - light.turn_on:
            id: bathroom_vanity_downlight
            brightness: 0.5
            red: 1.0
            green: 0.933
            blue: 0.753
            white: 1.0

switch:
  # motion activated lights enabler
  - platform: template
    id: bathroom_vanity_motion_activation
    name: ${node_friendly_name} Motion Activation
    optimistic: true
    restore_state: true

light:
  - platform: rgbw
    id: bathroom_vanity_uplight
    name: ${node_friendly_name} Uplight
    red: bathroom_vanity_uplight_pwm_red_channel
    green: bathroom_vanity_uplight_pwm_green_channel
    blue: bathroom_vanity_uplight_pwm_blue_channel
    white: bathroom_vanity_uplight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:
  - platform: rgbw
    id: bathroom_vanity_downlight
    name: ${node_friendly_name} Downlight
    red: bathroom_vanity_downlight_pwm_red_channel
    green: bathroom_vanity_downlight_pwm_green_channel
    blue: bathroom_vanity_downlight_pwm_blue_channel
    white: bathroom_vanity_downlight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_red_channel
    pin: GPIO16
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_green_channel
    pin: GPIO18
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_blue_channel
    pin: GPIO13
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_white_channel
    pin: GPIO27
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_red_channel
    pin: GPIO25
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_green_channel
    pin: GPIO26
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_blue_channel
    pin: GPIO33
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_white_channel
    pin: GPIO32