substitutions:
  node_name: esp-lights-neon-tester
  node_friendly_name: "Neon Tester"

packages:
  esp_common: !include ../shared/esp__common_core.yaml
  esp_lights_neon_base: !include ../shared/esp-lights-neon-base-v1.yaml