esphome:
  platformio_options:
    build_flags:
      - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
      - -DBOARD_HAS_PSRAM
      - -mfix-esp32-psram-cache-issue

esp32:
  board: featheresp32
  framework:
    type: arduino

substitutions:
  node_name: esp-thermostat-nextion-tester
  node_friendly_name: "Thermostat Board Tester"

packages:
  esp_common: !include ../shared/esp__common_core.yaml

status_led:
  pin:
    number: GPIO5
    inverted: true

time:
  - platform: homeassistant
    id: esptime

i2c:
  id: i2c_bus
  frequency: 400kHz
  sda: 21
  scl: 22
  scan: false

# spi:
#   clk_pin: GPIO14
#   mosi_pin: GPIO13
#   miso_pin: GPIO12

uart:
  id: nextion_uart
  tx_pin: GPIO19
  rx_pin: GPIO18
  baud_rate: 115200

mcp23017:
  - id: mcp23017_hub
    address: 0x20
    # open_drain_interrupt: 'true'

switch:
  - platform: gpio
    id: esp_thermostat_thermistor_vcc
    name: ${node_friendly_name} Thermistor Vcc
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      number: 33
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_mcp23017_reset
    name: ${node_friendly_name} MCP23017 Reset
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      number: 4
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: esp_thermostat_fan
    name: ${node_friendly_name} Fan
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 0
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_cool_1
    name: ${node_friendly_name} Cool 1
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 1
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_cool_2
    name: ${node_friendly_name} Cool 2
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 2
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_heat_1
    name: ${node_friendly_name} Heat 1
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 3
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_heat_2
    name: ${node_friendly_name} Heat 2
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 4
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_humidify
    name: ${node_friendly_name} Humidify
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 5
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_triac_misc_2
    name: ${node_friendly_name} Misc 2
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 6
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_triac_misc_3
    name: ${node_friendly_name} Misc 3
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 7
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_relay_1
    name: ${node_friendly_name} Relay 1
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 8
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_relay_2
    name: ${node_friendly_name} Relay 2
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_relay_3
    name: ${node_friendly_name} Relay 3
    # internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 10
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_to_1
    name: ${node_friendly_name} Test Output 1
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_to_2
    name: ${node_friendly_name} Test Output 2
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 12
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_to_3
    name: ${node_friendly_name} Test Output 3
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 13
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_to_4
    name: ${node_friendly_name} Test Output 4
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 14
      mode: OUTPUT
  - platform: gpio
    id: esp_thermostat_to_5
    name: ${node_friendly_name} Test Output 5
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_hub
      number: 15
      mode: OUTPUT

# BME680 BSEC sensor
bme680_bsec:
  address: 0x77

sensor:
  # Phototransistor ADC sensor
  # - platform: adc
  #   id: adc_sensor_phototransistor
  #   name: ${node_friendly_name} Phototransistor ADC
  #   pin: 32
  #   attenuation: 11db
  #   update_interval: 1s
  #   filters:
  #     - sliding_window_moving_average:
  #         window_size: 5
  #         send_every: 3
  #         send_first_at: 1
  #   on_value:
  #     then:
  #       - lambda: |-
  #           id(display_brightness) = clamp<float>(id(adc_sensor_phototransistor).state / 3.9, 0.05, 1);
  #           if (main_lcd != nullptr)
  #             main_lcd->set_backlight_brightness(id(display_brightness));
  # NTC thermistor ADC sensor
  # - platform: adc
  #   id: adc_sensor_thermistor
  #   name: ${node_friendly_name} Thermistor ADC
  #   pin: 34
  #   internal: true
  #   update_interval: never
  # NTC thermistor resistance sensor
  # - platform: resistance
  #   id: thermistor_sensor
  #   name: ${node_friendly_name} NTC Thermistor Resistance
  #   sensor: adc_sensor_thermistor
  #   configuration: DOWNSTREAM
  #   reference_voltage: 0.92V
  #   resistor: 10kOhm
  #   internal: true
  # NTC thermistor sensor
  # - platform: ntc
  #   id: esp_thermostat_thermistor_temperature
  #   name: ${node_friendly_name} NTC Thermistor Temperature
  #   sensor: thermistor_sensor
  #   calibration:
  #     b_constant: 3380
  #     reference_temperature: 25°C
  #     reference_resistance: 10kOhm
  #   filters:
  #     - sliding_window_moving_average:
  #         window_size: 5
  #         send_every: 1
  #         send_first_at: 1
  #   on_value:
  #     then:
  #       - lambda: |-
  #           std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_thermistor_temperature).state * 1.8 + 32) + "\xB0";
  #           id(nextionTextSensor6a).set_state(temperature_string, false, true);
  # DHT22 sensor
  # - platform: dht
  #   pin: GPIO23
  #   model: DHT22
  #   temperature:
  #     id: esp_thermostat_dht22_temperature
  #     name: ${node_friendly_name} DHT22 Temperature
  #     filters:
  #       - offset: -1.2
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_dht22_temperature).state * 1.8 + 32) + "\xB0";
  #             id(nextionTextSensor5a).set_state(temperature_string, false, true);
  #   humidity:
  #     id: esp_thermostat_dht22_humidity
  #     name: ${node_friendly_name} DHT22 Humidity
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_dht22_humidity).state) + "%";
  #             id(nextionTextSensor5b).set_state(humidity_string, false, true);
  #   update_interval: 15s
  # BME280 sensor
  - platform: bme280
    address: 0x76
    temperature:
      id: esp_thermostat_bme280_temperature
      name: ${node_friendly_name} BME280 Temperature
      filters:
        - offset: -0.5
    humidity:
      id: esp_thermostat_bme280_humidity
      name: ${node_friendly_name} BME280 Humidity
    pressure:
      id: esp_thermostat_bme280_pressure
      name: ${node_friendly_name} BME280 Pressure
    update_interval: 15s
  # BME680 BSEC sensor
  - platform: bme680_bsec
    temperature:
      id: esp_thermostat_bme680_temperature
      name: ${node_friendly_name} BME680 Temperature
      filters:
        - offset: -1.2
    humidity:
      id: esp_thermostat_bme680_humidity
      name: ${node_friendly_name} BME680 Humidity
    pressure:
      id: esp_thermostat_bme680_pressure
      name: ${node_friendly_name} BME680 Pressure
    gas_resistance:
      id: esp_thermostat_bme680_gas_resistance
      name: ${node_friendly_name} BME680 Gas Resistance
    iaq:
      id: esp_thermostat_bme680_iaq
      name: ${node_friendly_name} BME680 IAQ
    co2_equivalent:
      id: esp_thermostat_bme680_eco2
      name: ${node_friendly_name} BME680 eCO2
    breath_voc_equivalent:
      id: esp_thermostat_bme680_evoc
      name: ${node_friendly_name} BME680 Breath eVOC
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_thermostat_shtcx_temperature
      name: ${node_friendly_name} SHTC3 Temperature
      filters:
        - offset: -1.4
    humidity:
      id: esp_thermostat_shtcx_humidity
      name: ${node_friendly_name} SHTC3 Humidity
    update_interval: 15s
  # TMP117 sensor
  - platform: tmp117
    id: esp_thermostat_tmp117_temperature
    name: ${node_friendly_name} TMP117 Temperature
    filters:
      - offset: -1.5
    update_interval: 15s
  # SGP40 sensor
  - platform: sgp4x
    voc:
      id: esp_thermostat_sgp40_voc
      name: ${node_friendly_name} SGP40 VOC
      unit_of_measurement: VOC Index
    update_interval: 15s
    compensation:
      humidity_source: esp_thermostat_shtcx_humidity
      temperature_source: esp_thermostat_shtcx_temperature

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      id: esp_thermostat_bme680_accuracy
      name: ${node_friendly_name} BME680 Accuracy