substitutions:
  node_name: esp-lights-table-lamp-test
  node_friendly_name: "Lamp Test"

packages:
  esp_common: !include ../shared/esp__common_core.yaml

esphome:
  platform: ESP8266
  board: esp01_1m

i2c:
  id: i2c_bus
  frequency: 100kHz
  sda: 2
  scl: 14
  scan: true

# binary_sensor:
#   - platform: gpio
#     id: leds_off_button
#     pin:
#       number: GPIO0
#       inverted: true
#     on_click:
#       min_length: 50ms
#       max_length: 500ms
#       then:
#         - light.turn_off:
#             id: kitchen_under_cabinet_east
#         - light.turn_off:
#             id: kitchen_under_cabinet_west
#         - light.turn_off:
#             id: kitchen_uplight

light:
  - platform: rgbw
    id: lamp
    name: ${node_friendly_name} Light
    red: uplight_pwm_red_channel
    green: uplight_pwm_green_channel
    blue: uplight_pwm_blue_channel
    white: uplight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    id: uplight_pwm_red_channel
    pin: GPIO15
  - platform: esp8266_pwm
    id: uplight_pwm_green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: uplight_pwm_blue_channel
    pin: GPIO5
  - platform: esp8266_pwm
    id: uplight_pwm_white_channel
    pin: GPIO13