switch:
  # patch template switches to phyical switches so control is consistent
  - platform: template
    id: esp_thermostat_fan
    name: Fan
    optimistic: true
  - platform: template
    id: esp_thermostat_cool_1
    name: Cool 1
    optimistic: true
    turn_off_action:
      - switch.turn_off: esp_thermostat_cool_2
  - platform: template
    id: esp_thermostat_cool_2
    name: Cool 2
    optimistic: true
    turn_on_action:
      - switch.turn_on: esp_thermostat_cool_1
  - platform: template
    id: esp_thermostat_heat_1
    name: Heat 1
    optimistic: true
    turn_off_action:
      - switch.turn_off: esp_thermostat_heat_2
  - platform: template
    id: esp_thermostat_heat_2
    name: Heat 2
    optimistic: true
    turn_on_action:
      - switch.turn_on: esp_thermostat_heat_1
  - platform: template
    id: esp_thermostat_humidify
    name: Humidify
    optimistic: true
  # physical switches
  - platform: gpio
    id: esp_thermostat_thermistor_vcc
    name: Thermistor Vcc
    internal: true
    restore_mode: ALWAYS_ON
    pin:
      number: 33
      mode: OUTPUT
