
substitutions:
  home_page_name: "main"
  home_page_number: "0"
  setpoints_page_name: "main"
  setpoints_page_number: "0"
  sensors_page_name: "sensors"
  sensors_page_number: "3"
  weather_page_number: "4"
  weather_page_name: "weather"
  user_page_number: "1"
  user_page_name: "user"

  touch_up_heat: "11"
  touch_down_heat: "12"

  touch_up_cool: "14"
  touch_down_cool: "15"

  touch_down_hum: "0"
  touch_up_hum: "0"

  btnModeUpdate: "34"

  btnModeHeat: "21"
  btnModeCool: "20"
  btnModeFan: "19"
  btnModeOff: "18"

  swFanMode_number: "35"

  btnModeHeat_Pic_On: "17"
  btnModeHeat_Pic_Off: "16"

  btnModeCool_Pic_On: "12"
  btnModeCool_Pic_Off: "11"


  btnModeFan_Pic_On: "15"
  btnModeFan_Pic_Off: "14"
  btnModeFan_Pic_Auto: "13"
  main_background_off_pic: "1"
  main_background_cool_pic: "4"
  main_background_heat_pic: "3"
  main_background_fan_pic: "2"
  time_zone: "America/New_York"

packages:
  esp_common: !include esp__common_core.yaml
  esp_thermostat_common: !include esp_thermostat_nextion_common_no_rooms_config.yaml
  esp_thermostat_common_controller: !include esp_thermostat_common_thermo_controller_config.yaml
  esp__weather_sensor: !include esp__weather_sensor.yaml
  esp__iaq_sensor: !include esp__iaq_sensor.yaml
  esp__user_sensor: !include esp__user_sensor.yaml
  esp_thermostat_scripts: !include esp_thermostat_scripts.yaml
  esp__wifi_sensor: !include esp__wifi_sensor.yaml
  #esp__ha_sensor: !include esp__ha_sensor.yaml
  #esp__mqtt_sensor: !include esp__mqtt_sensor.yaml


# BME680 BSEC sensor
bme680_bsec:
  address: 0x76

interval:
  - interval: 5min
    then:
      - script.execute: update_weather
      - script.execute: update_iaq
      - script.execute: update_wifi

script:
  - id: update_loop
    then:
      - script.execute: update_user
      - script.execute: update_weather
      - script.execute: update_iaq
      - script.execute: update_wifi


sensor:
  # Phototransistor ADC sensor
  - platform: adc
    id: adc_sensor_phototransistor
    name: ${node_friendly_name} Phototransistor ADC
    pin: 32
    attenuation: 11db
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
          send_first_at: 1
    on_value:
      then:
        - lambda: |-
            id(display_brightness) = clamp(id(adc_sensor_phototransistor).state / 3.9, 0.05, 1);
            if (main_lcd != nullptr)
              main_lcd->set_backlight_brightness(id(display_brightness));
  # NTC thermistor ADC sensor
  - platform: adc
    id: adc_sensor_thermistor
    name: ${node_friendly_name} Thermistor ADC
    pin: 34
    internal: true
    update_interval: never
  # NTC thermistor resistance sensor
  - platform: resistance
    id: thermistor_sensor
    name: ${node_friendly_name} NTC Thermistor Resistance
    sensor: adc_sensor_thermistor
    configuration: DOWNSTREAM
    reference_voltage: 0.82V
    resistor: 10kOhm
    internal: true
  # NTC thermistor sensor
  - platform: ntc
    id: esp_thermostat_thermistor_temperature
    name: ${node_friendly_name} NTC Thermistor Temperature
    sensor: thermistor_sensor
    calibration:
      b_constant: 3380
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
          send_first_at: 1
    on_value:
      then:
        - lambda: |-
            std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_thermistor_temperature).state * 1.8 + 32) + "\xB0";
            id(textSensor6a).set_state(temperature_string, false, true);
  # BME680 BSEC sensor
  - platform: bme680_bsec
    temperature:
      #sample_rate: LP
      id: esp_thermostat_bme680_temperature
      name: ${node_friendly_name} BME680 Temperature
      filters:
        - offset: -1.2
      on_value:
        then:
          - lambda: |-
              std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_temperature).state * 1.8 + 32) + "\xB0";
              id(textSensor1a).set_state(temperature_string, false, true);
    humidity:
      id: esp_thermostat_bme680_humidity
      name: ${node_friendly_name} BME680 Humidity
      on_value:
        then:
          - lambda: |-
              std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_humidity).state) + "%";
              id(textSensor1b).set_state(humidity_string, false, true);
              esp32_thermostat::update_climate_table_humidity(id(climate_table_local_row), id(esp_thermostat_bme680_humidity).state);
    pressure:
      id: esp_thermostat_bme680_pressure
      name: ${node_friendly_name} BME680 Pressure
      on_value:
        then:
          - lambda: |-
              std::string pressure_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_pressure).state) + "hPa";
              id(textSensor1c).set_state(pressure_string, false, true);
    gas_resistance:
      id: esp_thermostat_bme680_gas_resistance
      name: ${node_friendly_name} BME680 Gas Resistance
      on_value:
        then:
          - lambda: |-
              std::string gas_res_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_gas_resistance).state);
              id(textSensor1d).set_state(gas_res_string, false, true);
    iaq:
      id: esp_thermostat_bme680_iaq
      name: ${node_friendly_name} BME680 IAQ
      on_value:
        then:
          - lambda: |-
              std::string iaq_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_iaq).state);
              id(textSensor1e).set_state(iaq_string, false, true);
              id(update_iaq).execute();

    co2_equivalent:
      id: esp_thermostat_bme680_eco2
      name: ${node_friendly_name} BME680 eCO2
    breath_voc_equivalent:
      id: esp_thermostat_bme680_evoc
      name: ${node_friendly_name} BME680 Breath eVOC
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_thermostat_shtcx_temperature
      name: ${node_friendly_name} SHTC3 Temperature
      filters:
        - offset: -1.4
      on_value:
        then:
          - lambda: |-
              std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_shtcx_temperature).state * 1.8 + 32) + "\xB0";
              id(textSensor3a).set_state(temperature_string, false, true);
    humidity:
      id: esp_thermostat_shtcx_humidity
      name: ${node_friendly_name} SHTC3 Humidity
      on_value:
        then:
          - lambda: |-
              std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_shtcx_humidity).state) + "%";
              id(textSensor3b).set_state(humidity_string, false, true);
    update_interval: 15s
  # TMP117 sensor
  - platform: tmp117
    id: esp_thermostat_tmp117_temperature
    name: ${node_friendly_name} TMP117 Temperature
    filters:
      - offset: -1.5
    on_value:
      then:
        - lambda: |-
            std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_tmp117_temperature).state * 1.8 + 32) + "\xB0";
            id(textSensor4a).set_state(temperature_string, false, true);
    update_interval: 15s
  # SGP40 sensor
  - platform: sgp40
    id: esp_thermostat_sgp40_voc
    name: ${node_friendly_name} SGP40 VOC
    update_interval: 15s
    compensation:
      humidity_source: esp_thermostat_shtcx_humidity
      temperature_source: esp_thermostat_shtcx_temperature
    on_value:
      then:
        - lambda: |-
            std::string voc_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_sgp40_voc).state);
            id(textSensor8d).set_state(voc_string, false, true);

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      id: esp_thermostat_bme680_accuracy
      name: ${node_friendly_name} BME680 Accuracy

display:
  - platform: nextion
    id: main_lcd
    uart_id: nextion_uart
    update_interval: 1s
    touch_sleep_timeout: 30
    auto_wake_on_touch: "true"
    on_setup:
      - delay: 3s
      - lambda: |-
          main_lcd->goto_page("main");
      - delay: 1s
      - lambda: |-
          esp32_thermostat::draw_main_screen(true);
      - script.execute: update_loop
    # tft_url: https://www.kbx81.net/download/public/NX8048K070.tft
    tft_url: http://nextionfw.thebakkers.com/Climate7.tft
    lambda: |-
      esp32_thermostat::draw_main_screen();
