substitutions:
  <<: !include esp__common_secrets.yaml

esphome:
  name: ${node_name}
  build_path: ../build/${node_name}

preferences:
  flash_write_interval: 2min

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API and define services
api:
  encryption:
    key: ${api_key}
  password: ${api_password}
  reboot_timeout: 120min

ota:
  password: ${ota_password}

button:
  - platform: restart
    name: ${node_friendly_name} Restart