substitutions:
  node_name: esp-lights-neon-rainbow
  node_friendly_name: "Neon Rainbow"
  dac_min_power: "0.08"
  dac_max_power: "0.96"

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_lights_neon_base: !include shared/esp-lights-neon-base-v2.yaml