substitutions:
  node_name: esp-thermostat-bathroom
  node_friendly_name: "Bathroom Thermostat"
  home_page_name: "home"
  rooms_page_name: "rooms"
  sensors_page_name: "sensors"
  weather_page_name: "weather"

packages:
  esp_common: !include ../shared/esp__common_core.yaml
  esp_thermostat_common: !include ../shared/esp_thermostat_nextion_common_config.yaml
  esp_thermostat_common_controller: !include ../shared/esp_thermostat_common_satellite_config.yaml

# BME680 BSEC sensor
bme680_bsec:
  address: 0x77

sensor:
  # Phototransistor ADC sensor
  - platform: adc
    id: adc_sensor_phototransistor
    name: Phototransistor ADC
    pin: 32
    attenuation: 11db
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
          send_first_at: 1
    on_value:
      then:
        - if:
            condition:
              switch.is_on: esp_thermostat_display_auto_brightness
            then:
              - lambda: |-
                  auto brightness_mult = id(motion_sense).is_running() || !id(esp_thermostat_display_on_motion).state ? 100 : (1.0 - id(esp_thermostat_display_brightness_idle_reduction).state) * 100;
                  auto number_call = id(esp_thermostat_display_brightness).make_call();
                  number_call.set_value(id(esp_thermostat_display).state ? clamp<float>(roundf(id(adc_sensor_phototransistor).state / 3.9 * brightness_mult), id(esp_thermostat_display_minimum_brightness).state, id(esp_thermostat_display_maximum_brightness).state) : 0);
                  number_call.perform();
  # NTC thermistor ADC sensor
  - platform: adc
    id: adc_sensor_thermistor
    name: Thermistor ADC
    pin: 34
    internal: true
    update_interval: 1s
  # NTC thermistor resistance sensor
  - platform: resistance
    id: thermistor_sensor
    name: NTC Thermistor Resistance
    sensor: adc_sensor_thermistor
    configuration: DOWNSTREAM
    reference_voltage: 0.86V
    resistor: 10kOhm
    internal: true
  # NTC thermistor sensor
  - platform: ntc
    id: esp_thermostat_thermistor_temperature
    name: NTC Thermistor Temperature
    sensor: thermistor_sensor
    calibration:
      b_constant: 3380
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 15
          send_first_at: 15
      - offset: -78
    on_value:
      then:
        - lambda: |-
            std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_thermistor_temperature).state * 1.8 + 32) + "\xB0";
            id(nextionTextSensor6a).set_state(temperature_string, false, true);
  # DHT22 sensor
  # - platform: dht
  #   pin: GPIO23
  #   model: DHT22
  #   temperature:
  #     id: esp_thermostat_dht22_temperature
  #     name: DHT22 Temperature
  #     filters:
  #       - offset: -3.2
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_dht22_temperature).state * 1.8 + 32) + "\xB0";
  #             id(nextionTextSensor5a).set_state(temperature_string, false, true);
  #   humidity:
  #     id: esp_thermostat_dht22_humidity
  #     name: DHT22 Humidity
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_dht22_humidity).state) + "%";
  #             id(nextionTextSensor5b).set_state(humidity_string, false, true);
  #   update_interval: 15s
  # BME280 sensor
  - platform: bme280
    address: 0x76
    temperature:
      id: esp_thermostat_bme280_temperature
      name: BME280 Temperature
      filters:
        - offset: -2.2
      on_value:
        then:
          - lambda: |-
              std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme280_temperature).state * 1.8 + 32) + "\xB0";
              id(nextionTextSensor2a).set_state(temperature_string, false, true);
    humidity:
      id: esp_thermostat_bme280_humidity
      name: BME280 Humidity
      on_value:
        then:
          - lambda: |-
              std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme280_humidity).state) + "%";
              id(nextionTextSensor2b).set_state(humidity_string, false, true);
    pressure:
      id: esp_thermostat_bme280_pressure
      name: BME280 Pressure
      on_value:
        then:
          - lambda: |-
              std::string pressure_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme280_pressure).state) + "hPa";
              id(nextionTextSensor2c).set_state(pressure_string, false, true);
    update_interval: 15s
  # BME680 BSEC sensor
  - platform: bme680_bsec
    temperature:
      id: esp_thermostat_bme680_temperature
      name: BME680 Temperature
      filters:
        - offset: -2.4
      on_value:
        then:
          - lambda: |-
              std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_temperature).state * 1.8 + 32) + "\xB0";
              id(nextionTextSensor1a).set_state(temperature_string, false, true);
              esp32_thermostat::display_refresh_table_temperature(id(climate_table_local_row), id(esp_thermostat_bme680_temperature).state);
    humidity:
      id: esp_thermostat_bme680_humidity
      name: BME680 Humidity
      on_value:
        then:
          - lambda: |-
              std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_humidity).state) + "%";
              id(nextionTextSensor1b).set_state(humidity_string, false, true);
              esp32_thermostat::display_refresh_table_humidity(id(climate_table_local_row), id(esp_thermostat_bme680_humidity).state);
    pressure:
      id: esp_thermostat_bme680_pressure
      name: BME680 Pressure
      on_value:
        then:
          - lambda: |-
              esp32_thermostat::display_refresh_sensor(id(esp_thermostat_bme680_pressure).state, esp32_thermostat::DS_CURRENT_PRES);
              std::string pressure_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_pressure).state) + "hPa";
              id(nextionTextSensor1c).set_state(pressure_string, false, true);
    gas_resistance:
      id: esp_thermostat_bme680_gas_resistance
      name: BME680 Gas Resistance
      # on_value:
      #   then:
      #     - lambda: |-
      #         std::string gas_res_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_gas_resistance).state);
      #         id(nextionTextSensor1d).set_state(gas_res_string, false, true);
    iaq:
      id: esp_thermostat_bme680_iaq
      name: BME680 IAQ
      on_value:
        then:
          - lambda: |-
              std::string iaq_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_iaq).state);
              id(nextionTextSensor1d).set_state(iaq_string, false, true);
              esp32_thermostat::display_refresh_iaq_txt(id(esp_thermostat_bme680_iaq).state);
    co2_equivalent:
      id: esp_thermostat_bme680_eco2
      name: BME680 eCO2
    breath_voc_equivalent:
      id: esp_thermostat_bme680_evoc
      name: BME680 Breath eVOC
  # BME680 sensor
  # - platform: bme680
  #   address: 0x77
  #   temperature:
  #     id: esp_thermostat_bme680_temperature
  #     name: BME680 Temperature
  #     filters:
  #       - offset: -1.2
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_temperature).state * 1.8 + 32) + "\xB0";
  #             id(nextionTextSensor1a).set_state(temperature_string, false, true);
  #             esp32_thermostat::display_refresh_table_temperature(id(climate_table_local_row), id(esp_thermostat_bme680_temperature).state);
  #   humidity:
  #     id: esp_thermostat_bme680_humidity
  #     name: BME680 Humidity
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_humidity).state) + "%";
  #             id(nextionTextSensor1b).set_state(humidity_string, false, true);
  #             esp32_thermostat::display_refresh_table_humidity(id(climate_table_local_row), id(esp_thermostat_bme680_humidity).state);
  #   pressure:
  #     id: esp_thermostat_bme680_pressure
  #     name: BME680 Pressure
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string pressure_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_pressure).state) + "hPa";
  #             id(nextionTextSensor1c).set_state(pressure_string, false, true);
  #   gas_resistance:
  #     id: esp_thermostat_bme680_gas_resistance
  #     name: BME680 Gas Resistance
  #     on_value:
  #       then:
  #         - lambda: |-
  #             std::string gas_res_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_bme680_gas_resistance).state);
  #             id(nextionTextSensor1d).set_state(gas_res_string, false, true);
  #   update_interval: 15s
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_thermostat_shtcx_temperature
      name: SHTC3 Temperature
      filters:
        - offset: -3.2
      on_value:
        then:
          - lambda: |-
              std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_shtcx_temperature).state * 1.8 + 32) + "\xB0";
              id(nextionTextSensor3a).set_state(temperature_string, false, true);
    humidity:
      id: esp_thermostat_shtcx_humidity
      name: SHTC3 Humidity
      on_value:
        then:
          - lambda: |-
              std::string humidity_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_shtcx_humidity).state) + "%";
              id(nextionTextSensor3b).set_state(humidity_string, false, true);
    update_interval: 15s
  # TMP117 sensor
  - platform: tmp117
    id: esp_thermostat_tmp117_temperature
    name: TMP117 Temperature
    filters:
      - offset: -3.6
    on_value:
      then:
        - lambda: |-
            std::string temperature_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_tmp117_temperature).state * 1.8 + 32) + "\xB0";
            id(nextionTextSensor4a).set_state(temperature_string, false, true);
    update_interval: 15s
  # SGP40 sensor
  - platform: sgp4x
    voc:
      id: esp_thermostat_sgp40_voc
      name: SGP40 VOC
      unit_of_measurement: VOC Index
      on_value:
        then:
          - lambda: |-
              std::string voc_string = esp32_thermostat::round_float_to_string(id(esp_thermostat_sgp40_voc).state);
              id(nextionTextSensor8d).set_state(voc_string, false, true);
    update_interval: 15s
    compensation:
      humidity_source: esp_thermostat_shtcx_humidity
      temperature_source: esp_thermostat_shtcx_temperature

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      id: esp_thermostat_bme680_accuracy
      name: BME680 Accuracy

display:
  - platform: nextion
    # test_debug: "true"
    id: main_lcd
    uart_id: nextion_uart
    update_interval: 15s
    # tft_url: https://www.kbx81.net/download/public/climate/NX4832K035.tft
    tft_url: http://10.100.0.51/download/public/climate/NX4832K035.tft
    lambda: "esp32_thermostat::draw_main_screen();"
    on_setup:
      then:
        - lambda: |-
            main_lcd->goto_page("home");
            esp32_thermostat::draw_main_screen(true);
