substitutions:
  node_name: esp-3ch-psu-controller
  node_friendly_name: "3 Channel PSU"

packages:
  esp_common: !include shared/esp__common_core.yaml

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: 0
    inverted: true

switch:
  - platform: gpio
    pin: 1
    name: Channel 1
    id: channel_1
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin: 2
    name: Channel 2
    id: channel_2
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin: 3
    name: Channel 3
    id: channel_3
    restore_mode: RESTORE_DEFAULT_ON