substitutions:
  node_name: esp-sensor-furnace-intake
  node_friendly_name: "Furnace Intake"

packages:
  esp_common: !include ../shared/esp__common_core.yaml

esphome:
  platform: ESP8266
  board: esp01_1m

i2c:
  id: i2c_bus
  frequency: 400kHz
  sda: GPIO2
  scl: GPIO0

# BME680 BSEC sensor
bme680_bsec:
  address: 0x76

sensor:
  # DHT22 sensor
  - platform: dht
    pin: GPIO3
    model: DHT22
    temperature:
      id: esp_sensor_dht22_temperature
      name: DHT22 Temperature
    humidity:
      id: esp_sensor_dht22_humidity
      name: DHT22 Humidity
    update_interval: 15s
  # BME680 BSEC sensor
  - platform: bme680_bsec
    temperature:
      id: esp_sensor_bme680_temperature
      name: BME680 Temperature
      filters:
        - offset: -0.9
    humidity:
      id: esp_sensor_bme680_humidity
      name: BME680 Humidity
    pressure:
      id: esp_sensor_bme680_pressure
      name: BME680 Pressure
    gas_resistance:
      id: esp_sensor_bme680_gas_resistance
      name: BME680 Gas Resistance
    iaq:
      id: esp_sensor_bme680_iaq
      name: BME680 IAQ
    co2_equivalent:
      id: esp_sensor_bme680_eco2
      name: BME680 eCO2
    breath_voc_equivalent:
      id: esp_sensor_bme680_evoc
      name: BME680 Breath eVOC
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_sensor_shtcx_temperature
      name: SHTC3 Temperature
      filters:
        - offset: -1.1
    humidity:
      id: esp_sensor_shtcx_humidity
      name: SHTC3 Humidity
    update_interval: 15s
  # SGP40 sensor
  - platform: sgp4x
    voc:
      id: esp_sensor_sgp40_voc
      name: SGP40 VOC
      unit_of_measurement: VOC Index
    update_interval: 15s
    compensation:
      humidity_source: esp_sensor_shtcx_humidity
      temperature_source: esp_sensor_shtcx_temperature

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      id: esp_sensor_bme680_accuracy
      name: BME680 Accuracy